/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea.analysis;

import java.util.*;
import tarea.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclarationStatement(ADeclarationStatement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrintExprStatement(APrintExprStatement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrintStringStatement(APrintStringStatement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrintlnExprStatement(APrintlnExprStatement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrintlnStringStatement(APrintlnStringStatement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInputStatement(AInputStatement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFlowControlStatement(AFlowControlStatement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInitializationStatement(AInitializationStatement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIncreaseVarStatement(AIncreaseVarStatement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecreaseVarStatement(ADecreaseVarStatement node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntDeclaration(AIntDeclaration node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringDeclaration(AStringDeclaration node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADoubleDeclaration(ADoubleDeclaration node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntInitializationDeclaration(AIntInitializationDeclaration node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringInitializationDeclaration(AStringInitializationDeclaration node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADoubleInitializationDeclaration(ADoubleInitializationDeclaration node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringInitialization(AStringInitialization node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExprInitialization(AExprInitialization node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIfFlowControl(AIfFlowControl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIfElseFlowControl(AIfElseFlowControl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAWhileFlowControl(AWhileFlowControl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAElseFlowControl(AElseFlowControl node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOtherCondition(AOtherCondition node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAndCondition(AAndCondition node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOrCondition(AOrCondition node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEqualsOther(AEqualsOther node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANotEqualsOther(ANotEqualsOther node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGreaterOther(AGreaterOther node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGreaterEqOther(AGreaterEqOther node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALessOther(ALessOther node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALessEqOther(ALessEqOther node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConditionOther(AConditionOther node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExprItem(AExprItem node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringItem(AStringItem node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANegativeExpr(ANegativeExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFactorExpr(AFactorExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPlusExpr(APlusExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMinusExpr(AMinusExpr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATermFactor(ATermFactor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultFactor(AMultFactor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivFactor(ADivFactor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAModFactor(AModFactor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumberTerm(ANumberTerm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarTerm(AVarTerm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExprTerm(AExprTerm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPlus(TPlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMinus(TMinus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMod(TMod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComment(TComment node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumber(TNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTStringLiteral(TStringLiteral node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInt(TInt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDouble(TDouble node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoublePlus(TDoublePlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoubleMinus(TDoubleMinus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLPar(TLPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRPar(TRPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNot(TNot node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSemicolon(TSemicolon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoubleEquals(TDoubleEquals node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEquals(TEquals node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLess(TLess node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGreater(TGreater node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnd(TAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOr(TOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIf(TIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTElse(TElse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLBrace(TLBrace node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRBrace(TRBrace node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPrint(TPrint node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPrintln(TPrintln node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMain(TMain node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWhile(TWhile node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInput(TInput node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVar(TVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
