/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea.analysis;

import tarea.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAMainProgram(AMainProgram node);
    void caseAFormatProgram(AFormatProgram node);
    void caseAIntDeclaration(AIntDeclaration node);
    void caseAStringDeclaration(AStringDeclaration node);
    void caseADoubleDeclaration(ADoubleDeclaration node);
    void caseAIntAssignmentDeclaration(AIntAssignmentDeclaration node);
    void caseAStringAssignmentDeclaration(AStringAssignmentDeclaration node);
    void caseADoubleAssignmentDeclaration(ADoubleAssignmentDeclaration node);
    void caseAPrintExprLine(APrintExprLine node);
    void caseAPrintStringLine(APrintStringLine node);
    void caseAPrintlnExprLine(APrintlnExprLine node);
    void caseAPrintlnStringLine(APrintlnStringLine node);
    void caseAInputLine(AInputLine node);
    void caseAFlowControlLine(AFlowControlLine node);
    void caseAAssignmentLine(AAssignmentLine node);
    void caseAIfFlowControl(AIfFlowControl node);
    void caseAIfElseFlowControl(AIfElseFlowControl node);
    void caseAWhileFlowControl(AWhileFlowControl node);
    void caseAElseStatement(AElseStatement node);
    void caseASecondConditionCondition(ASecondConditionCondition node);
    void caseAAndCondition(AAndCondition node);
    void caseAOrCondition(AOrCondition node);
    void caseAEqualsSecondCondition(AEqualsSecondCondition node);
    void caseANotEqualsSecondCondition(ANotEqualsSecondCondition node);
    void caseAGreaterSecondCondition(AGreaterSecondCondition node);
    void caseAGreaterEqSecondCondition(AGreaterEqSecondCondition node);
    void caseALessSecondCondition(ALessSecondCondition node);
    void caseALessEqSecondCondition(ALessEqSecondCondition node);
    void caseAGroupedSecondCondition(AGroupedSecondCondition node);
    void caseAExprItem(AExprItem node);
    void caseAStringItem(AStringItem node);
    void caseAStringAssignmentAssignment(AStringAssignmentAssignment node);
    void caseAExprAssignmentAssignment(AExprAssignmentAssignment node);
    void caseAFactorExpr(AFactorExpr node);
    void caseAPlusExpr(APlusExpr node);
    void caseAMinusExpr(AMinusExpr node);
    void caseATermFactor(ATermFactor node);
    void caseAMultFactor(AMultFactor node);
    void caseADivFactor(ADivFactor node);
    void caseAModFactor(AModFactor node);
    void caseANumberTerm(ANumberTerm node);
    void caseAVarTerm(AVarTerm node);
    void caseAExprTerm(AExprTerm node);

    void caseTComment(TComment node);
    void caseTNumber(TNumber node);
    void caseTStringLiteral(TStringLiteral node);
    void caseTInt(TInt node);
    void caseTDouble(TDouble node);
    void caseTString(TString node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTSemicolon(TSemicolon node);
    void caseTDoubleEquals(TDoubleEquals node);
    void caseTNotEquals(TNotEquals node);
    void caseTLessEq(TLessEq node);
    void caseTGreaterEq(TGreaterEq node);
    void caseTEquals(TEquals node);
    void caseTLess(TLess node);
    void caseTGreater(TGreater node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTPrint(TPrint node);
    void caseTPrintln(TPrintln node);
    void caseTMain(TMain node);
    void caseTWhile(TWhile node);
    void caseTInput(TInput node);
    void caseTVar(TVar node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
