/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea.analysis;

import java.util.*;
import tarea.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPMainProgram().apply(this);
        outStart(node);
    }

    public void inAMainProgram(AMainProgram node)
    {
        defaultIn(node);
    }

    public void outAMainProgram(AMainProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMainProgram(AMainProgram node)
    {
        inAMainProgram(node);
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        if(node.getProgram() != null)
        {
            node.getProgram().apply(this);
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getMain() != null)
        {
            node.getMain().apply(this);
        }
        outAMainProgram(node);
    }

    public void inAFormatProgram(AFormatProgram node)
    {
        defaultIn(node);
    }

    public void outAFormatProgram(AFormatProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFormatProgram(AFormatProgram node)
    {
        inAFormatProgram(node);
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            Collections.reverse(copy);
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PDeclaration> copy = new ArrayList<PDeclaration>(node.getDeclaration());
            Collections.reverse(copy);
            for(PDeclaration e : copy)
            {
                e.apply(this);
            }
        }
        outAFormatProgram(node);
    }

    public void inAIntDeclaration(AIntDeclaration node)
    {
        defaultIn(node);
    }

    public void outAIntDeclaration(AIntDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntDeclaration(AIntDeclaration node)
    {
        inAIntDeclaration(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        outAIntDeclaration(node);
    }

    public void inAStringDeclaration(AStringDeclaration node)
    {
        defaultIn(node);
    }

    public void outAStringDeclaration(AStringDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringDeclaration(AStringDeclaration node)
    {
        inAStringDeclaration(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringDeclaration(node);
    }

    public void inADoubleDeclaration(ADoubleDeclaration node)
    {
        defaultIn(node);
    }

    public void outADoubleDeclaration(ADoubleDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADoubleDeclaration(ADoubleDeclaration node)
    {
        inADoubleDeclaration(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getDouble() != null)
        {
            node.getDouble().apply(this);
        }
        outADoubleDeclaration(node);
    }

    public void inAIntAssignmentDeclaration(AIntAssignmentDeclaration node)
    {
        defaultIn(node);
    }

    public void outAIntAssignmentDeclaration(AIntAssignmentDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntAssignmentDeclaration(AIntAssignmentDeclaration node)
    {
        inAIntAssignmentDeclaration(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getAssignment() != null)
        {
            node.getAssignment().apply(this);
        }
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        outAIntAssignmentDeclaration(node);
    }

    public void inAStringAssignmentDeclaration(AStringAssignmentDeclaration node)
    {
        defaultIn(node);
    }

    public void outAStringAssignmentDeclaration(AStringAssignmentDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringAssignmentDeclaration(AStringAssignmentDeclaration node)
    {
        inAStringAssignmentDeclaration(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getAssignment() != null)
        {
            node.getAssignment().apply(this);
        }
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringAssignmentDeclaration(node);
    }

    public void inADoubleAssignmentDeclaration(ADoubleAssignmentDeclaration node)
    {
        defaultIn(node);
    }

    public void outADoubleAssignmentDeclaration(ADoubleAssignmentDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADoubleAssignmentDeclaration(ADoubleAssignmentDeclaration node)
    {
        inADoubleAssignmentDeclaration(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getAssignment() != null)
        {
            node.getAssignment().apply(this);
        }
        if(node.getDouble() != null)
        {
            node.getDouble().apply(this);
        }
        outADoubleAssignmentDeclaration(node);
    }

    public void inAPrintExprLine(APrintExprLine node)
    {
        defaultIn(node);
    }

    public void outAPrintExprLine(APrintExprLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintExprLine(APrintExprLine node)
    {
        inAPrintExprLine(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getPrint() != null)
        {
            node.getPrint().apply(this);
        }
        outAPrintExprLine(node);
    }

    public void inAPrintStringLine(APrintStringLine node)
    {
        defaultIn(node);
    }

    public void outAPrintStringLine(APrintStringLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintStringLine(APrintStringLine node)
    {
        inAPrintStringLine(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getStringLiteral() != null)
        {
            node.getStringLiteral().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getPrint() != null)
        {
            node.getPrint().apply(this);
        }
        outAPrintStringLine(node);
    }

    public void inAPrintlnExprLine(APrintlnExprLine node)
    {
        defaultIn(node);
    }

    public void outAPrintlnExprLine(APrintlnExprLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintlnExprLine(APrintlnExprLine node)
    {
        inAPrintlnExprLine(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getPrintln() != null)
        {
            node.getPrintln().apply(this);
        }
        outAPrintlnExprLine(node);
    }

    public void inAPrintlnStringLine(APrintlnStringLine node)
    {
        defaultIn(node);
    }

    public void outAPrintlnStringLine(APrintlnStringLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrintlnStringLine(APrintlnStringLine node)
    {
        inAPrintlnStringLine(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getStringLiteral() != null)
        {
            node.getStringLiteral().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getPrintln() != null)
        {
            node.getPrintln().apply(this);
        }
        outAPrintlnStringLine(node);
    }

    public void inAInputLine(AInputLine node)
    {
        defaultIn(node);
    }

    public void outAInputLine(AInputLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInputLine(AInputLine node)
    {
        inAInputLine(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getInput() != null)
        {
            node.getInput().apply(this);
        }
        outAInputLine(node);
    }

    public void inAFlowControlLine(AFlowControlLine node)
    {
        defaultIn(node);
    }

    public void outAFlowControlLine(AFlowControlLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFlowControlLine(AFlowControlLine node)
    {
        inAFlowControlLine(node);
        if(node.getFlowControl() != null)
        {
            node.getFlowControl().apply(this);
        }
        outAFlowControlLine(node);
    }

    public void inAAssignmentLine(AAssignmentLine node)
    {
        defaultIn(node);
    }

    public void outAAssignmentLine(AAssignmentLine node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignmentLine(AAssignmentLine node)
    {
        inAAssignmentLine(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getAssignment() != null)
        {
            node.getAssignment().apply(this);
        }
        outAAssignmentLine(node);
    }

    public void inAIfFlowControl(AIfFlowControl node)
    {
        defaultIn(node);
    }

    public void outAIfFlowControl(AIfFlowControl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfFlowControl(AIfFlowControl node)
    {
        inAIfFlowControl(node);
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            Collections.reverse(copy);
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outAIfFlowControl(node);
    }

    public void inAIfElseFlowControl(AIfElseFlowControl node)
    {
        defaultIn(node);
    }

    public void outAIfElseFlowControl(AIfElseFlowControl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfElseFlowControl(AIfElseFlowControl node)
    {
        inAIfElseFlowControl(node);
        if(node.getElseStatement() != null)
        {
            node.getElseStatement().apply(this);
        }
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            Collections.reverse(copy);
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outAIfElseFlowControl(node);
    }

    public void inAWhileFlowControl(AWhileFlowControl node)
    {
        defaultIn(node);
    }

    public void outAWhileFlowControl(AWhileFlowControl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileFlowControl(AWhileFlowControl node)
    {
        inAWhileFlowControl(node);
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            Collections.reverse(copy);
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        outAWhileFlowControl(node);
    }

    public void inAElseStatement(AElseStatement node)
    {
        defaultIn(node);
    }

    public void outAElseStatement(AElseStatement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseStatement(AElseStatement node)
    {
        inAElseStatement(node);
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        {
            List<PLine> copy = new ArrayList<PLine>(node.getLine());
            Collections.reverse(copy);
            for(PLine e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        outAElseStatement(node);
    }

    public void inASecondConditionCondition(ASecondConditionCondition node)
    {
        defaultIn(node);
    }

    public void outASecondConditionCondition(ASecondConditionCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASecondConditionCondition(ASecondConditionCondition node)
    {
        inASecondConditionCondition(node);
        if(node.getSecondCondition() != null)
        {
            node.getSecondCondition().apply(this);
        }
        outASecondConditionCondition(node);
    }

    public void inAAndCondition(AAndCondition node)
    {
        defaultIn(node);
    }

    public void outAAndCondition(AAndCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndCondition(AAndCondition node)
    {
        inAAndCondition(node);
        if(node.getSecondCondition() != null)
        {
            node.getSecondCondition().apply(this);
        }
        if(node.getAnd() != null)
        {
            node.getAnd().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        outAAndCondition(node);
    }

    public void inAOrCondition(AOrCondition node)
    {
        defaultIn(node);
    }

    public void outAOrCondition(AOrCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrCondition(AOrCondition node)
    {
        inAOrCondition(node);
        if(node.getSecondCondition() != null)
        {
            node.getSecondCondition().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        outAOrCondition(node);
    }

    public void inAEqualsSecondCondition(AEqualsSecondCondition node)
    {
        defaultIn(node);
    }

    public void outAEqualsSecondCondition(AEqualsSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEqualsSecondCondition(AEqualsSecondCondition node)
    {
        inAEqualsSecondCondition(node);
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        if(node.getDoubleEquals() != null)
        {
            node.getDoubleEquals().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAEqualsSecondCondition(node);
    }

    public void inANotEqualsSecondCondition(ANotEqualsSecondCondition node)
    {
        defaultIn(node);
    }

    public void outANotEqualsSecondCondition(ANotEqualsSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotEqualsSecondCondition(ANotEqualsSecondCondition node)
    {
        inANotEqualsSecondCondition(node);
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        if(node.getNotEquals() != null)
        {
            node.getNotEquals().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outANotEqualsSecondCondition(node);
    }

    public void inAGreaterSecondCondition(AGreaterSecondCondition node)
    {
        defaultIn(node);
    }

    public void outAGreaterSecondCondition(AGreaterSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGreaterSecondCondition(AGreaterSecondCondition node)
    {
        inAGreaterSecondCondition(node);
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        if(node.getGreater() != null)
        {
            node.getGreater().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAGreaterSecondCondition(node);
    }

    public void inAGreaterEqSecondCondition(AGreaterEqSecondCondition node)
    {
        defaultIn(node);
    }

    public void outAGreaterEqSecondCondition(AGreaterEqSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGreaterEqSecondCondition(AGreaterEqSecondCondition node)
    {
        inAGreaterEqSecondCondition(node);
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        if(node.getGreaterEq() != null)
        {
            node.getGreaterEq().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAGreaterEqSecondCondition(node);
    }

    public void inALessSecondCondition(ALessSecondCondition node)
    {
        defaultIn(node);
    }

    public void outALessSecondCondition(ALessSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALessSecondCondition(ALessSecondCondition node)
    {
        inALessSecondCondition(node);
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        if(node.getLess() != null)
        {
            node.getLess().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outALessSecondCondition(node);
    }

    public void inALessEqSecondCondition(ALessEqSecondCondition node)
    {
        defaultIn(node);
    }

    public void outALessEqSecondCondition(ALessEqSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALessEqSecondCondition(ALessEqSecondCondition node)
    {
        inALessEqSecondCondition(node);
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        if(node.getLessEq() != null)
        {
            node.getLessEq().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outALessEqSecondCondition(node);
    }

    public void inAGroupedSecondCondition(AGroupedSecondCondition node)
    {
        defaultIn(node);
    }

    public void outAGroupedSecondCondition(AGroupedSecondCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGroupedSecondCondition(AGroupedSecondCondition node)
    {
        inAGroupedSecondCondition(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        outAGroupedSecondCondition(node);
    }

    public void inAExprItem(AExprItem node)
    {
        defaultIn(node);
    }

    public void outAExprItem(AExprItem node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExprItem(AExprItem node)
    {
        inAExprItem(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAExprItem(node);
    }

    public void inAStringItem(AStringItem node)
    {
        defaultIn(node);
    }

    public void outAStringItem(AStringItem node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringItem(AStringItem node)
    {
        inAStringItem(node);
        if(node.getStringLiteral() != null)
        {
            node.getStringLiteral().apply(this);
        }
        outAStringItem(node);
    }

    public void inAStringAssignmentAssignment(AStringAssignmentAssignment node)
    {
        defaultIn(node);
    }

    public void outAStringAssignmentAssignment(AStringAssignmentAssignment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringAssignmentAssignment(AStringAssignmentAssignment node)
    {
        inAStringAssignmentAssignment(node);
        if(node.getStringLiteral() != null)
        {
            node.getStringLiteral().apply(this);
        }
        if(node.getEquals() != null)
        {
            node.getEquals().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAStringAssignmentAssignment(node);
    }

    public void inAExprAssignmentAssignment(AExprAssignmentAssignment node)
    {
        defaultIn(node);
    }

    public void outAExprAssignmentAssignment(AExprAssignmentAssignment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExprAssignmentAssignment(AExprAssignmentAssignment node)
    {
        inAExprAssignmentAssignment(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getEquals() != null)
        {
            node.getEquals().apply(this);
        }
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAExprAssignmentAssignment(node);
    }

    public void inAFactorExpr(AFactorExpr node)
    {
        defaultIn(node);
    }

    public void outAFactorExpr(AFactorExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFactorExpr(AFactorExpr node)
    {
        inAFactorExpr(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAFactorExpr(node);
    }

    public void inAPlusExpr(APlusExpr node)
    {
        defaultIn(node);
    }

    public void outAPlusExpr(APlusExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusExpr(APlusExpr node)
    {
        inAPlusExpr(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAPlusExpr(node);
    }

    public void inAMinusExpr(AMinusExpr node)
    {
        defaultIn(node);
    }

    public void outAMinusExpr(AMinusExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusExpr(AMinusExpr node)
    {
        inAMinusExpr(node);
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAMinusExpr(node);
    }

    public void inATermFactor(ATermFactor node)
    {
        defaultIn(node);
    }

    public void outATermFactor(ATermFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermFactor(ATermFactor node)
    {
        inATermFactor(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        outATermFactor(node);
    }

    public void inAMultFactor(AMultFactor node)
    {
        defaultIn(node);
    }

    public void outAMultFactor(AMultFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultFactor(AMultFactor node)
    {
        inAMultFactor(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAMultFactor(node);
    }

    public void inADivFactor(ADivFactor node)
    {
        defaultIn(node);
    }

    public void outADivFactor(ADivFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivFactor(ADivFactor node)
    {
        inADivFactor(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outADivFactor(node);
    }

    public void inAModFactor(AModFactor node)
    {
        defaultIn(node);
    }

    public void outAModFactor(AModFactor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAModFactor(AModFactor node)
    {
        inAModFactor(node);
        if(node.getTerm() != null)
        {
            node.getTerm().apply(this);
        }
        if(node.getMod() != null)
        {
            node.getMod().apply(this);
        }
        if(node.getFactor() != null)
        {
            node.getFactor().apply(this);
        }
        outAModFactor(node);
    }

    public void inANumberTerm(ANumberTerm node)
    {
        defaultIn(node);
    }

    public void outANumberTerm(ANumberTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberTerm(ANumberTerm node)
    {
        inANumberTerm(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outANumberTerm(node);
    }

    public void inAVarTerm(AVarTerm node)
    {
        defaultIn(node);
    }

    public void outAVarTerm(AVarTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarTerm(AVarTerm node)
    {
        inAVarTerm(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        outAVarTerm(node);
    }

    public void inAExprTerm(AExprTerm node)
    {
        defaultIn(node);
    }

    public void outAExprTerm(AExprTerm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExprTerm(AExprTerm node)
    {
        inAExprTerm(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        outAExprTerm(node);
    }
}
