/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea.parser;

import tarea.lexer.*;
import tarea.node.*;
import tarea.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgram node1 = (PProgram) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AProgram */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AAcontentformatcontent1Content */
            {
                ArrayList<Object> list = new1();
                push(goTo(1), list, false);
            }
            break;
            case 2: /* reduce AAcontentformatcontent2Content */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce AAcontentformatcontent3Content */
            {
                ArrayList<Object> list = new3();
                push(goTo(1), list, false);
            }
            break;
            case 4: /* reduce AAcontentformatcontent4Content */
            {
                ArrayList<Object> list = new4();
                push(goTo(1), list, false);
            }
            break;
            case 5: /* reduce AIntDeclaration */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list, false);
            }
            break;
            case 6: /* reduce AStringDeclaration */
            {
                ArrayList<Object> list = new6();
                push(goTo(2), list, false);
            }
            break;
            case 7: /* reduce ADoubleDeclaration */
            {
                ArrayList<Object> list = new7();
                push(goTo(2), list, false);
            }
            break;
            case 8: /* reduce AIntInitializationDeclaration */
            {
                ArrayList<Object> list = new8();
                push(goTo(2), list, false);
            }
            break;
            case 9: /* reduce AStringInitializationDeclaration */
            {
                ArrayList<Object> list = new9();
                push(goTo(2), list, false);
            }
            break;
            case 10: /* reduce ADoubleInitializationDeclaration */
            {
                ArrayList<Object> list = new10();
                push(goTo(2), list, false);
            }
            break;
            case 11: /* reduce APrintExprStatement */
            {
                ArrayList<Object> list = new11();
                push(goTo(3), list, false);
            }
            break;
            case 12: /* reduce APrintStringStatement */
            {
                ArrayList<Object> list = new12();
                push(goTo(3), list, false);
            }
            break;
            case 13: /* reduce APrintlnExprStatement */
            {
                ArrayList<Object> list = new13();
                push(goTo(3), list, false);
            }
            break;
            case 14: /* reduce APrintlnStringStatement */
            {
                ArrayList<Object> list = new14();
                push(goTo(3), list, false);
            }
            break;
            case 15: /* reduce AInputStatement */
            {
                ArrayList<Object> list = new15();
                push(goTo(3), list, false);
            }
            break;
            case 16: /* reduce AFlowControlStatement */
            {
                ArrayList<Object> list = new16();
                push(goTo(3), list, false);
            }
            break;
            case 17: /* reduce AInitializationStatement */
            {
                ArrayList<Object> list = new17();
                push(goTo(3), list, false);
            }
            break;
            case 18: /* reduce AIncreaseVarStatement */
            {
                ArrayList<Object> list = new18();
                push(goTo(3), list, false);
            }
            break;
            case 19: /* reduce ADecreaseVarStatement */
            {
                ArrayList<Object> list = new19();
                push(goTo(3), list, false);
            }
            break;
            case 20: /* reduce AStringInitialization */
            {
                ArrayList<Object> list = new20();
                push(goTo(4), list, false);
            }
            break;
            case 21: /* reduce AExprInitialization */
            {
                ArrayList<Object> list = new21();
                push(goTo(4), list, false);
            }
            break;
            case 22: /* reduce AAifflowcontrol1FlowControl */
            {
                ArrayList<Object> list = new22();
                push(goTo(5), list, false);
            }
            break;
            case 23: /* reduce AAifflowcontrol2FlowControl */
            {
                ArrayList<Object> list = new23();
                push(goTo(5), list, false);
            }
            break;
            case 24: /* reduce AAifelseflowcontrol1FlowControl */
            {
                ArrayList<Object> list = new24();
                push(goTo(5), list, false);
            }
            break;
            case 25: /* reduce AAifelseflowcontrol2FlowControl */
            {
                ArrayList<Object> list = new25();
                push(goTo(5), list, false);
            }
            break;
            case 26: /* reduce AAwhileflowcontrol1FlowControl */
            {
                ArrayList<Object> list = new26();
                push(goTo(5), list, false);
            }
            break;
            case 27: /* reduce AAwhileflowcontrol2FlowControl */
            {
                ArrayList<Object> list = new27();
                push(goTo(5), list, false);
            }
            break;
            case 28: /* reduce AAelseflowcontrol1ElseFlowControl */
            {
                ArrayList<Object> list = new28();
                push(goTo(6), list, false);
            }
            break;
            case 29: /* reduce AAelseflowcontrol2ElseFlowControl */
            {
                ArrayList<Object> list = new29();
                push(goTo(6), list, false);
            }
            break;
            case 30: /* reduce AOtherCondition */
            {
                ArrayList<Object> list = new30();
                push(goTo(7), list, false);
            }
            break;
            case 31: /* reduce AAndCondition */
            {
                ArrayList<Object> list = new31();
                push(goTo(7), list, false);
            }
            break;
            case 32: /* reduce AOrCondition */
            {
                ArrayList<Object> list = new32();
                push(goTo(7), list, false);
            }
            break;
            case 33: /* reduce AEqualsOther */
            {
                ArrayList<Object> list = new33();
                push(goTo(8), list, false);
            }
            break;
            case 34: /* reduce ANotEqualsOther */
            {
                ArrayList<Object> list = new34();
                push(goTo(8), list, false);
            }
            break;
            case 35: /* reduce AGreaterOther */
            {
                ArrayList<Object> list = new35();
                push(goTo(8), list, false);
            }
            break;
            case 36: /* reduce AGreaterEqOther */
            {
                ArrayList<Object> list = new36();
                push(goTo(8), list, false);
            }
            break;
            case 37: /* reduce ALessOther */
            {
                ArrayList<Object> list = new37();
                push(goTo(8), list, false);
            }
            break;
            case 38: /* reduce ALessEqOther */
            {
                ArrayList<Object> list = new38();
                push(goTo(8), list, false);
            }
            break;
            case 39: /* reduce AConditionOther */
            {
                ArrayList<Object> list = new39();
                push(goTo(8), list, false);
            }
            break;
            case 40: /* reduce AExprItem */
            {
                ArrayList<Object> list = new40();
                push(goTo(9), list, false);
            }
            break;
            case 41: /* reduce AStringItem */
            {
                ArrayList<Object> list = new41();
                push(goTo(9), list, false);
            }
            break;
            case 42: /* reduce ANegativeExpr */
            {
                ArrayList<Object> list = new42();
                push(goTo(10), list, false);
            }
            break;
            case 43: /* reduce AFactorExpr */
            {
                ArrayList<Object> list = new43();
                push(goTo(10), list, false);
            }
            break;
            case 44: /* reduce APlusExpr */
            {
                ArrayList<Object> list = new44();
                push(goTo(10), list, false);
            }
            break;
            case 45: /* reduce AMinusExpr */
            {
                ArrayList<Object> list = new45();
                push(goTo(10), list, false);
            }
            break;
            case 46: /* reduce ATermFactor */
            {
                ArrayList<Object> list = new46();
                push(goTo(11), list, false);
            }
            break;
            case 47: /* reduce AMultFactor */
            {
                ArrayList<Object> list = new47();
                push(goTo(11), list, false);
            }
            break;
            case 48: /* reduce ADivFactor */
            {
                ArrayList<Object> list = new48();
                push(goTo(11), list, false);
            }
            break;
            case 49: /* reduce AModFactor */
            {
                ArrayList<Object> list = new49();
                push(goTo(11), list, false);
            }
            break;
            case 50: /* reduce ANumberTerm */
            {
                ArrayList<Object> list = new50();
                push(goTo(12), list, false);
            }
            break;
            case 51: /* reduce AVarTerm */
            {
                ArrayList<Object> list = new51();
                push(goTo(12), list, false);
            }
            break;
            case 52: /* reduce AExprTerm */
            {
                ArrayList<Object> list = new52();
                push(goTo(12), list, false);
            }
            break;
            case 53: /* reduce ATerminal$Declaration */
            {
                ArrayList<Object> list = new53();
                push(goTo(13), list, true);
            }
            break;
            case 54: /* reduce ANonTerminal$Declaration */
            {
                ArrayList<Object> list = new54();
                push(goTo(13), list, true);
            }
            break;
            case 55: /* reduce ATerminal$Statement */
            {
                ArrayList<Object> list = new55();
                push(goTo(14), list, true);
            }
            break;
            case 56: /* reduce ANonTerminal$Statement */
            {
                ArrayList<Object> list = new56();
                push(goTo(14), list, true);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AProgram */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        TMain tmainNode2;
        TLPar tlparNode3;
        TRPar trparNode4;
        TLBrace tlbraceNode5;
        PContent pcontentNode6;
        TRBrace trbraceNode7;
        tmainNode2 = (TMain)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        trparNode4 = (TRPar)nodeArrayList3.get(0);
        tlbraceNode5 = (TLBrace)nodeArrayList4.get(0);
        pcontentNode6 = (PContent)nodeArrayList5.get(0);
        trbraceNode7 = (TRBrace)nodeArrayList6.get(0);

        pprogramNode1 = new AProgram(tmainNode2, tlparNode3, trparNode4, tlbraceNode5, pcontentNode6, trbraceNode7);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AAcontentformatcontent1Content */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PContent pcontentNode1;
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        }
        {
            // Block
        }

        pcontentNode1 = new AContentFormatContent(listNode2, listNode3);
        }
	nodeList.add(pcontentNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AAcontentformatcontent2Content */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContent pcontentNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        }

        pcontentNode1 = new AContentFormatContent(listNode3, listNode4);
        }
	nodeList.add(pcontentNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AAcontentformatcontent3Content */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContent pcontentNode1;
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        {
            // Block
        }
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList1.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pcontentNode1 = new AContentFormatContent(listNode2, listNode4);
        }
	nodeList.add(pcontentNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AAcontentformatcontent4Content */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContent pcontentNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pcontentNode1 = new AContentFormatContent(listNode3, listNode5);
        }
	nodeList.add(pcontentNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce AIntDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TInt tintNode2;
        TVar tvarNode3;
        TSemicolon tsemicolonNode4;
        tintNode2 = (TInt)nodeArrayList1.get(0);
        tvarNode3 = (TVar)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new AIntDeclaration(tintNode2, tvarNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce AStringDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TString tstringNode2;
        TVar tvarNode3;
        TSemicolon tsemicolonNode4;
        tstringNode2 = (TString)nodeArrayList1.get(0);
        tvarNode3 = (TVar)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new AStringDeclaration(tstringNode2, tvarNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce ADoubleDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TDouble tdoubleNode2;
        TVar tvarNode3;
        TSemicolon tsemicolonNode4;
        tdoubleNode2 = (TDouble)nodeArrayList1.get(0);
        tvarNode3 = (TVar)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new ADoubleDeclaration(tdoubleNode2, tvarNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce AIntInitializationDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TInt tintNode2;
        PInitialization pinitializationNode3;
        TSemicolon tsemicolonNode4;
        tintNode2 = (TInt)nodeArrayList1.get(0);
        pinitializationNode3 = (PInitialization)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new AIntInitializationDeclaration(tintNode2, pinitializationNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AStringInitializationDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TString tstringNode2;
        PInitialization pinitializationNode3;
        TSemicolon tsemicolonNode4;
        tstringNode2 = (TString)nodeArrayList1.get(0);
        pinitializationNode3 = (PInitialization)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new AStringInitializationDeclaration(tstringNode2, pinitializationNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce ADoubleInitializationDeclaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclaration pdeclarationNode1;
        {
            // Block
        TDouble tdoubleNode2;
        PInitialization pinitializationNode3;
        TSemicolon tsemicolonNode4;
        tdoubleNode2 = (TDouble)nodeArrayList1.get(0);
        pinitializationNode3 = (PInitialization)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pdeclarationNode1 = new ADoubleInitializationDeclaration(tdoubleNode2, pinitializationNode3, tsemicolonNode4);
        }
	nodeList.add(pdeclarationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce APrintExprStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TPrint tprintNode2;
        TLPar tlparNode3;
        PExpr pexprNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tprintNode2 = (TPrint)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pexprNode4 = (PExpr)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        pstatementNode1 = new APrintExprStatement(tprintNode2, tlparNode3, pexprNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce APrintStringStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TPrint tprintNode2;
        TLPar tlparNode3;
        TStringLiteral tstringliteralNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tprintNode2 = (TPrint)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        tstringliteralNode4 = (TStringLiteral)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        pstatementNode1 = new APrintStringStatement(tprintNode2, tlparNode3, tstringliteralNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce APrintlnExprStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TPrintln tprintlnNode2;
        TLPar tlparNode3;
        PExpr pexprNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tprintlnNode2 = (TPrintln)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pexprNode4 = (PExpr)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        pstatementNode1 = new APrintlnExprStatement(tprintlnNode2, tlparNode3, pexprNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce APrintlnStringStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TPrintln tprintlnNode2;
        TLPar tlparNode3;
        TStringLiteral tstringliteralNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tprintlnNode2 = (TPrintln)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        tstringliteralNode4 = (TStringLiteral)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        pstatementNode1 = new APrintlnStringStatement(tprintlnNode2, tlparNode3, tstringliteralNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce AInputStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TInput tinputNode2;
        TLPar tlparNode3;
        TVar tvarNode4;
        TRPar trparNode5;
        TSemicolon tsemicolonNode6;
        tinputNode2 = (TInput)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        tvarNode4 = (TVar)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tsemicolonNode6 = (TSemicolon)nodeArrayList5.get(0);

        pstatementNode1 = new AInputStatement(tinputNode2, tlparNode3, tvarNode4, trparNode5, tsemicolonNode6);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce AFlowControlStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PFlowControl pflowcontrolNode2;
        pflowcontrolNode2 = (PFlowControl)nodeArrayList1.get(0);

        pstatementNode1 = new AFlowControlStatement(pflowcontrolNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce AInitializationStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PInitialization pinitializationNode2;
        TSemicolon tsemicolonNode3;
        pinitializationNode2 = (PInitialization)nodeArrayList1.get(0);
        tsemicolonNode3 = (TSemicolon)nodeArrayList2.get(0);

        pstatementNode1 = new AInitializationStatement(pinitializationNode2, tsemicolonNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce AIncreaseVarStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TVar tvarNode2;
        TDoublePlus tdoubleplusNode3;
        TSemicolon tsemicolonNode4;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tdoubleplusNode3 = (TDoublePlus)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pstatementNode1 = new AIncreaseVarStatement(tvarNode2, tdoubleplusNode3, tsemicolonNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce ADecreaseVarStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TVar tvarNode2;
        TDoubleMinus tdoubleminusNode3;
        TSemicolon tsemicolonNode4;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tdoubleminusNode3 = (TDoubleMinus)nodeArrayList2.get(0);
        tsemicolonNode4 = (TSemicolon)nodeArrayList3.get(0);

        pstatementNode1 = new ADecreaseVarStatement(tvarNode2, tdoubleminusNode3, tsemicolonNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce AStringInitialization */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInitialization pinitializationNode1;
        {
            // Block
        TVar tvarNode2;
        TEquals tequalsNode3;
        TStringLiteral tstringliteralNode4;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tequalsNode3 = (TEquals)nodeArrayList2.get(0);
        tstringliteralNode4 = (TStringLiteral)nodeArrayList3.get(0);

        pinitializationNode1 = new AStringInitialization(tvarNode2, tequalsNode3, tstringliteralNode4);
        }
	nodeList.add(pinitializationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce AExprInitialization */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInitialization pinitializationNode1;
        {
            // Block
        TVar tvarNode2;
        TEquals tequalsNode3;
        PExpr pexprNode4;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tequalsNode3 = (TEquals)nodeArrayList2.get(0);
        pexprNode4 = (PExpr)nodeArrayList3.get(0);

        pinitializationNode1 = new AExprInitialization(tvarNode2, tequalsNode3, pexprNode4);
        }
	nodeList.add(pinitializationNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AAifflowcontrol1FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TIf tifNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBrace tlbraceNode6;
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        TRBrace trbraceNode8;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbraceNode6 = (TLBrace)nodeArrayList5.get(0);
        {
            // Block
        }
        trbraceNode8 = (TRBrace)nodeArrayList6.get(0);

        pflowcontrolNode1 = new AIfFlowControl(tifNode2, tlparNode3, pconditionNode4, trparNode5, tlbraceNode6, listNode7, trbraceNode8);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce AAifflowcontrol2FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TIf tifNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBrace tlbraceNode6;
        LinkedList<Object> listNode8 = new LinkedList<Object>();
        TRBrace trbraceNode9;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbraceNode6 = (TLBrace)nodeArrayList5.get(0);
        {
            // Block
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        listNode7 = (LinkedList)nodeArrayList6.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
        trbraceNode9 = (TRBrace)nodeArrayList7.get(0);

        pflowcontrolNode1 = new AIfFlowControl(tifNode2, tlparNode3, pconditionNode4, trparNode5, tlbraceNode6, listNode8, trbraceNode9);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce AAifelseflowcontrol1FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TIf tifNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBrace tlbraceNode6;
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        TRBrace trbraceNode8;
        PElseFlowControl pelseflowcontrolNode9;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbraceNode6 = (TLBrace)nodeArrayList5.get(0);
        {
            // Block
        }
        trbraceNode8 = (TRBrace)nodeArrayList6.get(0);
        pelseflowcontrolNode9 = (PElseFlowControl)nodeArrayList7.get(0);

        pflowcontrolNode1 = new AIfElseFlowControl(tifNode2, tlparNode3, pconditionNode4, trparNode5, tlbraceNode6, listNode7, trbraceNode8, pelseflowcontrolNode9);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce AAifelseflowcontrol2FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TIf tifNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBrace tlbraceNode6;
        LinkedList<Object> listNode8 = new LinkedList<Object>();
        TRBrace trbraceNode9;
        PElseFlowControl pelseflowcontrolNode10;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbraceNode6 = (TLBrace)nodeArrayList5.get(0);
        {
            // Block
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        listNode7 = (LinkedList)nodeArrayList6.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
        trbraceNode9 = (TRBrace)nodeArrayList7.get(0);
        pelseflowcontrolNode10 = (PElseFlowControl)nodeArrayList8.get(0);

        pflowcontrolNode1 = new AIfElseFlowControl(tifNode2, tlparNode3, pconditionNode4, trparNode5, tlbraceNode6, listNode8, trbraceNode9, pelseflowcontrolNode10);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce AAwhileflowcontrol1FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TWhile twhileNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBrace tlbraceNode6;
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        TRBrace trbraceNode8;
        twhileNode2 = (TWhile)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbraceNode6 = (TLBrace)nodeArrayList5.get(0);
        {
            // Block
        }
        trbraceNode8 = (TRBrace)nodeArrayList6.get(0);

        pflowcontrolNode1 = new AWhileFlowControl(twhileNode2, tlparNode3, pconditionNode4, trparNode5, tlbraceNode6, listNode7, trbraceNode8);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AAwhileflowcontrol2FlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFlowControl pflowcontrolNode1;
        {
            // Block
        TWhile twhileNode2;
        TLPar tlparNode3;
        PCondition pconditionNode4;
        TRPar trparNode5;
        TLBrace tlbraceNode6;
        LinkedList<Object> listNode8 = new LinkedList<Object>();
        TRBrace trbraceNode9;
        twhileNode2 = (TWhile)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pconditionNode4 = (PCondition)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tlbraceNode6 = (TLBrace)nodeArrayList5.get(0);
        {
            // Block
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        listNode7 = (LinkedList)nodeArrayList6.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
        trbraceNode9 = (TRBrace)nodeArrayList7.get(0);

        pflowcontrolNode1 = new AWhileFlowControl(twhileNode2, tlparNode3, pconditionNode4, trparNode5, tlbraceNode6, listNode8, trbraceNode9);
        }
	nodeList.add(pflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce AAelseflowcontrol1ElseFlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElseFlowControl pelseflowcontrolNode1;
        {
            // Block
        TElse telseNode2;
        TLBrace tlbraceNode3;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        TRBrace trbraceNode5;
        telseNode2 = (TElse)nodeArrayList1.get(0);
        tlbraceNode3 = (TLBrace)nodeArrayList2.get(0);
        {
            // Block
        }
        trbraceNode5 = (TRBrace)nodeArrayList3.get(0);

        pelseflowcontrolNode1 = new AElseFlowControl(telseNode2, tlbraceNode3, listNode4, trbraceNode5);
        }
	nodeList.add(pelseflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce AAelseflowcontrol2ElseFlowControl */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PElseFlowControl pelseflowcontrolNode1;
        {
            // Block
        TElse telseNode2;
        TLBrace tlbraceNode3;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        TRBrace trbraceNode6;
        telseNode2 = (TElse)nodeArrayList1.get(0);
        tlbraceNode3 = (TLBrace)nodeArrayList2.get(0);
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        trbraceNode6 = (TRBrace)nodeArrayList4.get(0);

        pelseflowcontrolNode1 = new AElseFlowControl(telseNode2, tlbraceNode3, listNode5, trbraceNode6);
        }
	nodeList.add(pelseflowcontrolNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce AOtherCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCondition pconditionNode1;
        {
            // Block
        POther potherNode2;
        potherNode2 = (POther)nodeArrayList1.get(0);

        pconditionNode1 = new AOtherCondition(potherNode2);
        }
	nodeList.add(pconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce AAndCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCondition pconditionNode1;
        {
            // Block
        PCondition pconditionNode2;
        TAnd tandNode3;
        POther potherNode4;
        pconditionNode2 = (PCondition)nodeArrayList1.get(0);
        tandNode3 = (TAnd)nodeArrayList2.get(0);
        potherNode4 = (POther)nodeArrayList3.get(0);

        pconditionNode1 = new AAndCondition(pconditionNode2, tandNode3, potherNode4);
        }
	nodeList.add(pconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce AOrCondition */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PCondition pconditionNode1;
        {
            // Block
        PCondition pconditionNode2;
        TOr torNode3;
        POther potherNode4;
        pconditionNode2 = (PCondition)nodeArrayList1.get(0);
        torNode3 = (TOr)nodeArrayList2.get(0);
        potherNode4 = (POther)nodeArrayList3.get(0);

        pconditionNode1 = new AOrCondition(pconditionNode2, torNode3, potherNode4);
        }
	nodeList.add(pconditionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce AEqualsOther */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POther potherNode1;
        {
            // Block
        TVar tvarNode2;
        TDoubleEquals tdoubleequalsNode3;
        PItem pitemNode4;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tdoubleequalsNode3 = (TDoubleEquals)nodeArrayList2.get(0);
        pitemNode4 = (PItem)nodeArrayList3.get(0);

        potherNode1 = new AEqualsOther(tvarNode2, tdoubleequalsNode3, pitemNode4);
        }
	nodeList.add(potherNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce ANotEqualsOther */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POther potherNode1;
        {
            // Block
        TVar tvarNode2;
        TNot tnotNode3;
        TEquals tequalsNode4;
        PItem pitemNode5;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tnotNode3 = (TNot)nodeArrayList2.get(0);
        tequalsNode4 = (TEquals)nodeArrayList3.get(0);
        pitemNode5 = (PItem)nodeArrayList4.get(0);

        potherNode1 = new ANotEqualsOther(tvarNode2, tnotNode3, tequalsNode4, pitemNode5);
        }
	nodeList.add(potherNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AGreaterOther */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POther potherNode1;
        {
            // Block
        TVar tvarNode2;
        TGreater tgreaterNode3;
        PItem pitemNode4;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tgreaterNode3 = (TGreater)nodeArrayList2.get(0);
        pitemNode4 = (PItem)nodeArrayList3.get(0);

        potherNode1 = new AGreaterOther(tvarNode2, tgreaterNode3, pitemNode4);
        }
	nodeList.add(potherNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce AGreaterEqOther */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POther potherNode1;
        {
            // Block
        TVar tvarNode2;
        TGreater tgreaterNode3;
        TEquals tequalsNode4;
        PItem pitemNode5;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tgreaterNode3 = (TGreater)nodeArrayList2.get(0);
        tequalsNode4 = (TEquals)nodeArrayList3.get(0);
        pitemNode5 = (PItem)nodeArrayList4.get(0);

        potherNode1 = new AGreaterEqOther(tvarNode2, tgreaterNode3, tequalsNode4, pitemNode5);
        }
	nodeList.add(potherNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce ALessOther */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POther potherNode1;
        {
            // Block
        TVar tvarNode2;
        TLess tlessNode3;
        PItem pitemNode4;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tlessNode3 = (TLess)nodeArrayList2.get(0);
        pitemNode4 = (PItem)nodeArrayList3.get(0);

        potherNode1 = new ALessOther(tvarNode2, tlessNode3, pitemNode4);
        }
	nodeList.add(potherNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce ALessEqOther */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POther potherNode1;
        {
            // Block
        TVar tvarNode2;
        TLess tlessNode3;
        TEquals tequalsNode4;
        PItem pitemNode5;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tlessNode3 = (TLess)nodeArrayList2.get(0);
        tequalsNode4 = (TEquals)nodeArrayList3.get(0);
        pitemNode5 = (PItem)nodeArrayList4.get(0);

        potherNode1 = new ALessEqOther(tvarNode2, tlessNode3, tequalsNode4, pitemNode5);
        }
	nodeList.add(potherNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce AConditionOther */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POther potherNode1;
        {
            // Block
        TLPar tlparNode2;
        PCondition pconditionNode3;
        TRPar trparNode4;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pconditionNode3 = (PCondition)nodeArrayList2.get(0);
        trparNode4 = (TRPar)nodeArrayList3.get(0);

        potherNode1 = new AConditionOther(tlparNode2, pconditionNode3, trparNode4);
        }
	nodeList.add(potherNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce AExprItem */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItem pitemNode1;
        {
            // Block
        PExpr pexprNode2;
        pexprNode2 = (PExpr)nodeArrayList1.get(0);

        pitemNode1 = new AExprItem(pexprNode2);
        }
	nodeList.add(pitemNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce AStringItem */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PItem pitemNode1;
        {
            // Block
        TStringLiteral tstringliteralNode2;
        tstringliteralNode2 = (TStringLiteral)nodeArrayList1.get(0);

        pitemNode1 = new AStringItem(tstringliteralNode2);
        }
	nodeList.add(pitemNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce ANegativeExpr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        TMinus tminusNode2;
        PFactor pfactorNode3;
        tminusNode2 = (TMinus)nodeArrayList1.get(0);
        pfactorNode3 = (PFactor)nodeArrayList2.get(0);

        pexprNode1 = new ANegativeExpr(tminusNode2, pfactorNode3);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce AFactorExpr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PFactor pfactorNode2;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);

        pexprNode1 = new AFactorExpr(pfactorNode2);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce APlusExpr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PExpr pexprNode2;
        TPlus tplusNode3;
        PFactor pfactorNode4;
        pexprNode2 = (PExpr)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        pfactorNode4 = (PFactor)nodeArrayList3.get(0);

        pexprNode1 = new APlusExpr(pexprNode2, tplusNode3, pfactorNode4);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce AMinusExpr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PExpr pexprNode2;
        TMinus tminusNode3;
        PFactor pfactorNode4;
        pexprNode2 = (PExpr)nodeArrayList1.get(0);
        tminusNode3 = (TMinus)nodeArrayList2.get(0);
        pfactorNode4 = (PFactor)nodeArrayList3.get(0);

        pexprNode1 = new AMinusExpr(pexprNode2, tminusNode3, pfactorNode4);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce ATermFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        PTerm ptermNode2;
        ptermNode2 = (PTerm)nodeArrayList1.get(0);

        pfactorNode1 = new ATermFactor(ptermNode2);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce AMultFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        PFactor pfactorNode2;
        TMult tmultNode3;
        PTerm ptermNode4;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);
        tmultNode3 = (TMult)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        pfactorNode1 = new AMultFactor(pfactorNode2, tmultNode3, ptermNode4);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce ADivFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        PFactor pfactorNode2;
        TDiv tdivNode3;
        PTerm ptermNode4;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);
        tdivNode3 = (TDiv)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        pfactorNode1 = new ADivFactor(pfactorNode2, tdivNode3, ptermNode4);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce AModFactor */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        PFactor pfactorNode2;
        TMod tmodNode3;
        PTerm ptermNode4;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);
        tmodNode3 = (TMod)nodeArrayList2.get(0);
        ptermNode4 = (PTerm)nodeArrayList3.get(0);

        pfactorNode1 = new AModFactor(pfactorNode2, tmodNode3, ptermNode4);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce ANumberTerm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        ptermNode1 = new ANumberTerm(tnumberNode2);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new51() /* reduce AVarTerm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TVar tvarNode2;
        tvarNode2 = (TVar)nodeArrayList1.get(0);

        ptermNode1 = new AVarTerm(tvarNode2);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new52() /* reduce AExprTerm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        TLPar tlparNode2;
        PExpr pexprNode3;
        TRPar trparNode4;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pexprNode3 = (PExpr)nodeArrayList2.get(0);
        trparNode4 = (TRPar)nodeArrayList3.get(0);

        ptermNode1 = new AExprTerm(tlparNode2, pexprNode3, trparNode4);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new53() /* reduce ATerminal$Declaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PDeclaration pdeclarationNode1;
        pdeclarationNode1 = (PDeclaration)nodeArrayList1.get(0);
	if(pdeclarationNode1 != null)
	{
	  listNode2.add(pdeclarationNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new54() /* reduce ANonTerminal$Declaration */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PDeclaration pdeclarationNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pdeclarationNode2 = (PDeclaration)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pdeclarationNode2 != null)
	{
	  listNode3.add(pdeclarationNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new55() /* reduce ATerminal$Statement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PStatement pstatementNode1;
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
	if(pstatementNode1 != null)
	{
	  listNode2.add(pstatementNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new56() /* reduce ANonTerminal$Statement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PStatement pstatementNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pstatementNode2 = (PStatement)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pstatementNode2 != null)
	{
	  listNode3.add(pstatementNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {28, SHIFT, 1}, },
			{{-1, ERROR, 1}, {12, SHIFT, 3}, },
			{{-1, ERROR, 2}, {32, ACCEPT, -1}, },
			{{-1, ERROR, 3}, {13, SHIFT, 4}, },
			{{-1, ERROR, 4}, {24, SHIFT, 5}, },
			{{-1, REDUCE, 1}, {7, SHIFT, 6}, {8, SHIFT, 7}, {9, SHIFT, 8}, {22, SHIFT, 9}, {26, SHIFT, 10}, {27, SHIFT, 11}, {29, SHIFT, 12}, {30, SHIFT, 13}, {31, SHIFT, 14}, },
			{{-1, ERROR, 6}, {31, SHIFT, 22}, },
			{{-1, ERROR, 7}, {31, SHIFT, 24}, },
			{{-1, ERROR, 8}, {31, SHIFT, 26}, },
			{{-1, ERROR, 9}, {12, SHIFT, 28}, },
			{{-1, ERROR, 10}, {12, SHIFT, 29}, },
			{{-1, ERROR, 11}, {12, SHIFT, 30}, },
			{{-1, ERROR, 12}, {12, SHIFT, 31}, },
			{{-1, ERROR, 13}, {12, SHIFT, 32}, },
			{{-1, ERROR, 14}, {10, SHIFT, 33}, {11, SHIFT, 34}, {17, SHIFT, 35}, },
			{{-1, ERROR, 15}, {25, SHIFT, 36}, },
			{{-1, REDUCE, 53}, },
			{{-1, REDUCE, 55}, },
			{{-1, ERROR, 18}, {15, SHIFT, 37}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 2}, {7, SHIFT, 6}, {8, SHIFT, 7}, {9, SHIFT, 8}, {22, SHIFT, 9}, {26, SHIFT, 10}, {27, SHIFT, 11}, {29, SHIFT, 12}, {30, SHIFT, 13}, {31, SHIFT, 14}, },
			{{-1, REDUCE, 3}, {22, SHIFT, 9}, {26, SHIFT, 10}, {27, SHIFT, 11}, {29, SHIFT, 12}, {30, SHIFT, 13}, {31, SHIFT, 14}, },
			{{-1, ERROR, 22}, {15, SHIFT, 41}, {17, SHIFT, 35}, },
			{{-1, ERROR, 23}, {15, SHIFT, 42}, },
			{{-1, ERROR, 24}, {15, SHIFT, 43}, {17, SHIFT, 35}, },
			{{-1, ERROR, 25}, {15, SHIFT, 44}, },
			{{-1, ERROR, 26}, {15, SHIFT, 45}, {17, SHIFT, 35}, },
			{{-1, ERROR, 27}, {15, SHIFT, 46}, },
			{{-1, ERROR, 28}, {12, SHIFT, 47}, {31, SHIFT, 48}, },
			{{-1, ERROR, 29}, {3, SHIFT, 51}, {5, SHIFT, 52}, {6, SHIFT, 53}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, ERROR, 30}, {3, SHIFT, 51}, {5, SHIFT, 52}, {6, SHIFT, 59}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, ERROR, 31}, {12, SHIFT, 47}, {31, SHIFT, 48}, },
			{{-1, ERROR, 32}, {31, SHIFT, 62}, },
			{{-1, ERROR, 33}, {15, SHIFT, 63}, },
			{{-1, ERROR, 34}, {15, SHIFT, 64}, },
			{{-1, ERROR, 35}, {3, SHIFT, 51}, {5, SHIFT, 52}, {6, SHIFT, 65}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, REDUCE, 0}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 54}, },
			{{-1, REDUCE, 4}, {22, SHIFT, 9}, {26, SHIFT, 10}, {27, SHIFT, 11}, {29, SHIFT, 12}, {30, SHIFT, 13}, {31, SHIFT, 14}, },
			{{-1, REDUCE, 56}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 47}, {12, SHIFT, 47}, {31, SHIFT, 48}, },
			{{-1, ERROR, 48}, {14, SHIFT, 68}, {16, SHIFT, 69}, {18, SHIFT, 70}, {19, SHIFT, 71}, },
			{{-1, ERROR, 49}, {13, SHIFT, 72}, {20, SHIFT, 73}, {21, SHIFT, 74}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 51}, {5, SHIFT, 52}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, REDUCE, 50}, },
			{{-1, ERROR, 53}, {13, SHIFT, 76}, },
			{{-1, ERROR, 54}, {3, SHIFT, 51}, {5, SHIFT, 52}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, REDUCE, 51}, },
			{{-1, ERROR, 56}, {2, SHIFT, 78}, {3, SHIFT, 79}, {13, SHIFT, 80}, },
			{{-1, REDUCE, 43}, {0, SHIFT, 81}, {1, SHIFT, 82}, {4, SHIFT, 83}, },
			{{-1, REDUCE, 46}, },
			{{-1, ERROR, 59}, {13, SHIFT, 84}, },
			{{-1, ERROR, 60}, {2, SHIFT, 78}, {3, SHIFT, 79}, {13, SHIFT, 85}, },
			{{-1, ERROR, 61}, {13, SHIFT, 86}, {20, SHIFT, 73}, {21, SHIFT, 74}, },
			{{-1, ERROR, 62}, {13, SHIFT, 87}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 20}, },
			{{-1, REDUCE, 21}, {2, SHIFT, 78}, {3, SHIFT, 79}, },
			{{-1, ERROR, 67}, {13, SHIFT, 88}, {20, SHIFT, 73}, {21, SHIFT, 74}, },
			{{-1, ERROR, 68}, {17, SHIFT, 89}, },
			{{-1, ERROR, 69}, {3, SHIFT, 51}, {5, SHIFT, 52}, {6, SHIFT, 90}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, ERROR, 70}, {3, SHIFT, 51}, {5, SHIFT, 52}, {6, SHIFT, 90}, {12, SHIFT, 54}, {17, SHIFT, 93}, {31, SHIFT, 55}, },
			{{-1, ERROR, 71}, {3, SHIFT, 51}, {5, SHIFT, 52}, {6, SHIFT, 90}, {12, SHIFT, 54}, {17, SHIFT, 95}, {31, SHIFT, 55}, },
			{{-1, ERROR, 72}, {24, SHIFT, 97}, },
			{{-1, ERROR, 73}, {12, SHIFT, 47}, {31, SHIFT, 48}, },
			{{-1, ERROR, 74}, {12, SHIFT, 47}, {31, SHIFT, 48}, },
			{{-1, REDUCE, 42}, {0, SHIFT, 81}, {1, SHIFT, 82}, {4, SHIFT, 83}, },
			{{-1, ERROR, 76}, {15, SHIFT, 100}, },
			{{-1, ERROR, 77}, {2, SHIFT, 78}, {3, SHIFT, 79}, {13, SHIFT, 101}, },
			{{-1, ERROR, 78}, {5, SHIFT, 52}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, ERROR, 79}, {5, SHIFT, 52}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, ERROR, 80}, {15, SHIFT, 104}, },
			{{-1, ERROR, 81}, {5, SHIFT, 52}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, ERROR, 82}, {5, SHIFT, 52}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, ERROR, 83}, {5, SHIFT, 52}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, ERROR, 84}, {15, SHIFT, 108}, },
			{{-1, ERROR, 85}, {15, SHIFT, 109}, },
			{{-1, ERROR, 86}, {24, SHIFT, 110}, },
			{{-1, ERROR, 87}, {15, SHIFT, 111}, },
			{{-1, REDUCE, 39}, },
			{{-1, ERROR, 89}, {3, SHIFT, 51}, {5, SHIFT, 52}, {6, SHIFT, 90}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, REDUCE, 41}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 40}, {2, SHIFT, 78}, {3, SHIFT, 79}, },
			{{-1, ERROR, 93}, {3, SHIFT, 51}, {5, SHIFT, 52}, {6, SHIFT, 90}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, REDUCE, 37}, },
			{{-1, ERROR, 95}, {3, SHIFT, 51}, {5, SHIFT, 52}, {6, SHIFT, 90}, {12, SHIFT, 54}, {31, SHIFT, 55}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 97}, {22, SHIFT, 9}, {25, SHIFT, 115}, {26, SHIFT, 10}, {27, SHIFT, 11}, {29, SHIFT, 12}, {30, SHIFT, 13}, {31, SHIFT, 14}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 44}, {0, SHIFT, 81}, {1, SHIFT, 82}, {4, SHIFT, 83}, },
			{{-1, REDUCE, 45}, {0, SHIFT, 81}, {1, SHIFT, 82}, {4, SHIFT, 83}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 110}, {22, SHIFT, 9}, {25, SHIFT, 117}, {26, SHIFT, 10}, {27, SHIFT, 11}, {29, SHIFT, 12}, {30, SHIFT, 13}, {31, SHIFT, 14}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 34}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 22}, {23, SHIFT, 119}, },
			{{-1, ERROR, 116}, {22, SHIFT, 9}, {25, SHIFT, 121}, {26, SHIFT, 10}, {27, SHIFT, 11}, {29, SHIFT, 12}, {30, SHIFT, 13}, {31, SHIFT, 14}, },
			{{-1, REDUCE, 26}, },
			{{-1, ERROR, 118}, {22, SHIFT, 9}, {25, SHIFT, 122}, {26, SHIFT, 10}, {27, SHIFT, 11}, {29, SHIFT, 12}, {30, SHIFT, 13}, {31, SHIFT, 14}, },
			{{-1, ERROR, 119}, {24, SHIFT, 123}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 23}, {23, SHIFT, 119}, },
			{{-1, REDUCE, 27}, },
			{{-1, ERROR, 123}, {22, SHIFT, 9}, {25, SHIFT, 125}, {26, SHIFT, 10}, {27, SHIFT, 11}, {29, SHIFT, 12}, {30, SHIFT, 13}, {31, SHIFT, 14}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 126}, {22, SHIFT, 9}, {25, SHIFT, 127}, {26, SHIFT, 10}, {27, SHIFT, 11}, {29, SHIFT, 12}, {30, SHIFT, 13}, {31, SHIFT, 14}, },
			{{-1, REDUCE, 29}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 15}, },
			{{-1, 16}, {20, 38}, },
			{{-1, 17}, {21, 40}, {39, 40}, {116, 40}, {118, 40}, {126, 40}, },
			{{-1, 18}, {6, 23}, {7, 25}, {8, 27}, },
			{{-1, 19}, },
			{{-1, 120}, {121, 124}, },
			{{-1, 49}, {31, 61}, {47, 67}, },
			{{-1, 50}, {73, 98}, {74, 99}, },
			{{-1, 91}, {70, 94}, {71, 96}, {89, 112}, {93, 113}, {95, 114}, },
			{{-1, 92}, {29, 56}, {30, 60}, {35, 66}, {54, 77}, },
			{{-1, 57}, {51, 75}, {78, 102}, {79, 103}, },
			{{-1, 58}, {81, 105}, {82, 106}, {83, 107}, },
			{{-1, 20}, },
			{{-1, 21}, {20, 39}, {97, 116}, {110, 118}, {123, 126}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'main'",
			"expecting: '('",
			"expecting: EOF",
			"expecting: ')'",
			"expecting: '{'",
			"expecting: 'int', 'double', 'string', 'if', '}', 'print', 'println', 'while', 'input', var",
			"expecting: var",
			"expecting: '++', '--', '='",
			"expecting: '}'",
			"expecting: 'if', '}', 'print', 'println', 'while', 'input', var",
			"expecting: ';'",
			"expecting: ';', '='",
			"expecting: '(', var",
			"expecting: '-', number, string literal, '(', var",
			"expecting: '!', '==', '<', '>'",
			"expecting: ')', '&&', '||'",
			"expecting: number, '(', var",
			"expecting: '*', '/', '+', '-', '%', ')', ';', '&&', '||'",
			"expecting: '-', number, '(', var",
			"expecting: '+', '-', ')'",
			"expecting: '+', '-', ';'",
			"expecting: '='",
			"expecting: '-', number, string literal, '(', '=', var",
			"expecting: '+', '-', ')', '&&', '||'",
			"expecting: 'if', 'else', '}', 'print', 'println', 'while', 'input', var",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 5, 6, 6, 6, 1, 1, 1, 1, 1, 7, 8, 5, 9, 10, 9, 5, 9, 11, 10, 11, 10, 11, 10, 12, 13, 13, 12, 6, 10, 10, 13, 2, 9, 5, 9, 9, 5, 5, 5, 5, 5, 5, 12, 14, 15, 15, 16, 17, 3, 18, 17, 19, 17, 17, 3, 19, 15, 3, 9, 9, 10, 20, 15, 21, 13, 22, 22, 4, 12, 12, 17, 10, 19, 16, 16, 10, 16, 16, 16, 10, 10, 4, 10, 15, 13, 15, 15, 23, 13, 15, 13, 15, 9, 15, 15, 9, 17, 17, 17, 9, 17, 17, 17, 9, 9, 9, 9, 15, 15, 15, 24, 9, 9, 9, 4, 9, 24, 9, 9, 9, 9, 9, 9, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
