/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea.node;

import tarea.analysis.*;

@SuppressWarnings("nls")
public final class ADecreaseVarStatement extends PStatement
{
    private TVar _var_;
    private TDoubleMinus _doubleMinus_;
    private TSemicolon _semicolon_;

    public ADecreaseVarStatement()
    {
        // Constructor
    }

    public ADecreaseVarStatement(
        @SuppressWarnings("hiding") TVar _var_,
        @SuppressWarnings("hiding") TDoubleMinus _doubleMinus_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setVar(_var_);

        setDoubleMinus(_doubleMinus_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new ADecreaseVarStatement(
            cloneNode(this._var_),
            cloneNode(this._doubleMinus_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecreaseVarStatement(this);
    }

    public TVar getVar()
    {
        return this._var_;
    }

    public void setVar(TVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TDoubleMinus getDoubleMinus()
    {
        return this._doubleMinus_;
    }

    public void setDoubleMinus(TDoubleMinus node)
    {
        if(this._doubleMinus_ != null)
        {
            this._doubleMinus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doubleMinus_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._doubleMinus_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._doubleMinus_ == child)
        {
            this._doubleMinus_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((TVar) newChild);
            return;
        }

        if(this._doubleMinus_ == oldChild)
        {
            setDoubleMinus((TDoubleMinus) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
