/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea.node;

import tarea.analysis.*;

@SuppressWarnings("nls")
public final class AFlowControlStatement extends PStatement
{
    private PFlowControl _flowControl_;

    public AFlowControlStatement()
    {
        // Constructor
    }

    public AFlowControlStatement(
        @SuppressWarnings("hiding") PFlowControl _flowControl_)
    {
        // Constructor
        setFlowControl(_flowControl_);

    }

    @Override
    public Object clone()
    {
        return new AFlowControlStatement(
            cloneNode(this._flowControl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFlowControlStatement(this);
    }

    public PFlowControl getFlowControl()
    {
        return this._flowControl_;
    }

    public void setFlowControl(PFlowControl node)
    {
        if(this._flowControl_ != null)
        {
            this._flowControl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._flowControl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._flowControl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._flowControl_ == child)
        {
            this._flowControl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._flowControl_ == oldChild)
        {
            setFlowControl((PFlowControl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
