/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea.node;

import tarea.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterEqOther extends POther
{
    private TVar _var_;
    private TGreater _greater_;
    private TEquals _equals_;
    private PItem _item_;

    public AGreaterEqOther()
    {
        // Constructor
    }

    public AGreaterEqOther(
        @SuppressWarnings("hiding") TVar _var_,
        @SuppressWarnings("hiding") TGreater _greater_,
        @SuppressWarnings("hiding") TEquals _equals_,
        @SuppressWarnings("hiding") PItem _item_)
    {
        // Constructor
        setVar(_var_);

        setGreater(_greater_);

        setEquals(_equals_);

        setItem(_item_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterEqOther(
            cloneNode(this._var_),
            cloneNode(this._greater_),
            cloneNode(this._equals_),
            cloneNode(this._item_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterEqOther(this);
    }

    public TVar getVar()
    {
        return this._var_;
    }

    public void setVar(TVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TGreater getGreater()
    {
        return this._greater_;
    }

    public void setGreater(TGreater node)
    {
        if(this._greater_ != null)
        {
            this._greater_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greater_ = node;
    }

    public TEquals getEquals()
    {
        return this._equals_;
    }

    public void setEquals(TEquals node)
    {
        if(this._equals_ != null)
        {
            this._equals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equals_ = node;
    }

    public PItem getItem()
    {
        return this._item_;
    }

    public void setItem(PItem node)
    {
        if(this._item_ != null)
        {
            this._item_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._item_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._greater_)
            + toString(this._equals_)
            + toString(this._item_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._greater_ == child)
        {
            this._greater_ = null;
            return;
        }

        if(this._equals_ == child)
        {
            this._equals_ = null;
            return;
        }

        if(this._item_ == child)
        {
            this._item_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((TVar) newChild);
            return;
        }

        if(this._greater_ == oldChild)
        {
            setGreater((TGreater) newChild);
            return;
        }

        if(this._equals_ == oldChild)
        {
            setEquals((TEquals) newChild);
            return;
        }

        if(this._item_ == oldChild)
        {
            setItem((PItem) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
