/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea.node;

import tarea.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterEqSecondCondition extends PSecondCondition
{
    private TVar _var_;
    private TGreaterEq _greaterEq_;
    private PItem _item_;

    public AGreaterEqSecondCondition()
    {
        // Constructor
    }

    public AGreaterEqSecondCondition(
        @SuppressWarnings("hiding") TVar _var_,
        @SuppressWarnings("hiding") TGreaterEq _greaterEq_,
        @SuppressWarnings("hiding") PItem _item_)
    {
        // Constructor
        setVar(_var_);

        setGreaterEq(_greaterEq_);

        setItem(_item_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterEqSecondCondition(
            cloneNode(this._var_),
            cloneNode(this._greaterEq_),
            cloneNode(this._item_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterEqSecondCondition(this);
    }

    public TVar getVar()
    {
        return this._var_;
    }

    public void setVar(TVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TGreaterEq getGreaterEq()
    {
        return this._greaterEq_;
    }

    public void setGreaterEq(TGreaterEq node)
    {
        if(this._greaterEq_ != null)
        {
            this._greaterEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterEq_ = node;
    }

    public PItem getItem()
    {
        return this._item_;
    }

    public void setItem(PItem node)
    {
        if(this._item_ != null)
        {
            this._item_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._item_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._greaterEq_)
            + toString(this._item_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._greaterEq_ == child)
        {
            this._greaterEq_ = null;
            return;
        }

        if(this._item_ == child)
        {
            this._item_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((TVar) newChild);
            return;
        }

        if(this._greaterEq_ == oldChild)
        {
            setGreaterEq((TGreaterEq) newChild);
            return;
        }

        if(this._item_ == oldChild)
        {
            setItem((PItem) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
