/* This file was generated by SableCC (http://www.sablecc.org/). */

package tarea.node;

import tarea.analysis.*;

@SuppressWarnings("nls")
public final class ALessEqSecondCondition extends PSecondCondition
{
    private TVar _var_;
    private TLessEq _lessEq_;
    private PItem _item_;

    public ALessEqSecondCondition()
    {
        // Constructor
    }

    public ALessEqSecondCondition(
        @SuppressWarnings("hiding") TVar _var_,
        @SuppressWarnings("hiding") TLessEq _lessEq_,
        @SuppressWarnings("hiding") PItem _item_)
    {
        // Constructor
        setVar(_var_);

        setLessEq(_lessEq_);

        setItem(_item_);

    }

    @Override
    public Object clone()
    {
        return new ALessEqSecondCondition(
            cloneNode(this._var_),
            cloneNode(this._lessEq_),
            cloneNode(this._item_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessEqSecondCondition(this);
    }

    public TVar getVar()
    {
        return this._var_;
    }

    public void setVar(TVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TLessEq getLessEq()
    {
        return this._lessEq_;
    }

    public void setLessEq(TLessEq node)
    {
        if(this._lessEq_ != null)
        {
            this._lessEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lessEq_ = node;
    }

    public PItem getItem()
    {
        return this._item_;
    }

    public void setItem(PItem node)
    {
        if(this._item_ != null)
        {
            this._item_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._item_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._lessEq_)
            + toString(this._item_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._lessEq_ == child)
        {
            this._lessEq_ = null;
            return;
        }

        if(this._item_ == child)
        {
            this._item_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((TVar) newChild);
            return;
        }

        if(this._lessEq_ == oldChild)
        {
            setLessEq((TLessEq) newChild);
            return;
        }

        if(this._item_ == oldChild)
        {
            setItem((PItem) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
